### ISSUE TITLE
Nothing actually works (models, enlightn, ER Diagram, tests)

### ISSUE THREAD

**Issue by saiht** [beyondcode/invoker-community#334] opened 2023-03-14 13:32 UTC
------
**OS**: darwin
**Invoker Version**: 2.11.0
**Laravel Version**: 10.3.3
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=Domains%5CCommerce%5CCatalog%5CModels%5CProduct&time=1678800575747&project=local-nq7sJCQj5umWKC95xznAca

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at /Projects/pro/cqrs-test/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1112
    1108▕     public function getDoctrineSchemaManager()
    1109▕     {
    1110▕         $connection = $this->getDoctrineConnection();
    1111▕ 
  ➜ 1112▕         return $connection->createSchemaManager();
    1113▕     }
    1114▕ 
    1115▕     /**
    1116▕      * Get the Doctrine DBAL database connection instance.

  1   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox8e7f5be646a5\Invoker\Factories\AttributeCollection::getColumns("Domains\Commerce\Catalog\Models\Product")
```

**Comment by wivaku** [comment] 2023-03-14 15:10
duplicate of #332 ?

**Comment by mechelon** [comment] 2023-03-16 10:50
Yup, duplicate of #332

**Closed as completed by mechelon** 2023-03-16 10:50 UTC
