### ISSUE TITLE
 Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare

### ISSUE THREAD

**Issue by elsayed85** [beyondcode/invoker-community#206] opened 2021-06-01 19:12 UTC
------
**OS**: win32
**Invoker Version**: 2.5.0
**Laravel Version**: 8.42.1
**Local project**: true
**PHP Binary**: C:\xampp\php\php.exe
**Route**: /project/index?class=App%5CModels%5CTransmission&time=1622574679160&project=local-5gSWwP2pUnpZXjU5ZwTed8

**Error**:
```
Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = Array) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement

  at phar://C:/Users/INTEL/AppData/Local/Programs/Invoker/resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41
     37▕     public function getServerVersion()
     38▕     {
     39▕         return \PDO::getAttribute(\PDO::ATTR_SERVER_VERSION);
     40▕     }
  ➜  41▕     public function prepare($sql, $driverOptions = [])
     42▕     {
     43▕         try {
     44▕             $statement = parent::prepare($sql, $driverOptions);
     45▕             \assert($statement instanceof \PDOStatement);


   Whoops\Exception\ErrorException 

  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = Array) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement

  at phar://C:/Users/INTEL/AppData/Local/Programs/Invoker/resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41
     37▕     public function getServerVersion()
     38▕     {
     39▕         return \PDO::getAttribute(\PDO::ATTR_SERVER_VERSION);
     40▕     }
  ➜  41▕     public function prepare($sql, $driverOptions = [])
     42▕     {
     43▕         try {
     44▕             $statement = parent::prepare($sql, $driverOptions);
     45▕             \assert($statement instanceof \PDOStatement);

  1   D:\cloudvests\auction\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = Array) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement", "phar://C:/Users/INTEL/AppData/Local/Programs/Invoker/resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()
```

**Comment by tfevens** [comment] 2021-06-02 01:35
Duplicate of #205

**Comment by sschlein** [comment] 2021-06-10 08:16
Closing because of #205

**Closed by sschlein** 2021-06-10 08:16 UTC
