### ISSUE TITLE
ParseToAstFailure with Eloquent Prunable - can't load jobs & events

### ISSUE THREAD

**Issue by AshPowell** [beyondcode/invoker-community#309] opened 2022-09-09 11:08 UTC
------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: 9.28.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /events?project=local-8vzhqCCExyYJHoQgugjWiN

**Error**:
```
_HumbugBoxf4b902e0e9ad\Roave\BetterReflection\SourceLocator\Ast\Exception\ParseToAstFailure 

  AST failed to parse in located source (in /Users/ashpowell/Projects/Website54/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Prunable.php)

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/roave/better-reflection/src/SourceLocator/Ast/Exception/ParseToAstFailure.php:22
     18▕         }
     19▕         if ($additionalInformation === '') {
     20▕             $additionalInformation = \sprintf(' (first 20 characters: %s)', \substr($locatedSource->getSource(), 0, 20));
     21▕         }
  ➜  22▕         return new self(\sprintf('AST failed to parse in located source%s', $additionalInformation), 0, $previous);
     23▕     }
     24▕ }
     25▕

      [2m+1 vendor frames [22m
  2   [internal]:0
      _HumbugBoxf4b902e0e9ad\Roave\BetterReflection\Reflection\ReflectionClass::_HumbugBoxf4b902e0e9ad\Roave\BetterReflection\Reflection\{closure}(Object(_HumbugBoxf4b902e0e9ad\PhpParser\Node\Name\FullyQualified))

  3   [internal]:0
      _HumbugBoxf4b902e0e9ad\Invoker\ModelLookupService::_HumbugBoxf4b902e0e9ad\Invoker\{closure}(Object(_HumbugBoxf4b902e0e9ad\Invoker\Factories\PhpFileItem))
```

**Comment by mpociot** [comment] 2022-12-01 11:39
Duplicate of #320

**Closed as completed by mpociot** 2022-12-01 11:39 UTC
