### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

### ISSUE THREAD

**Issue by WA-MB** [beyondcode/invoker-community#346] opened 2023-07-10 09:34 UTC
------
**OS**: win32
**Invoker Version**: 2.9.0
**Laravel Version**: 10.14.1
**Local project**: true
**PHP Binary**: C:\php\php.exe
**Route**: /project/index?class=App%5CModels%5CUser&time=1688981520122&project=local-rHN5HpsrWVpi59n11EvgSs

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:1210
    1206▕     public function getDoctrineSchemaManager()
    1207▕     {
    1208▕         $connection = $this->getDoctrineConnection();
    1209▕ 
  ➜ 1210▕         return $connection->createSchemaManager();
    1211▕     }
    1212▕ 
    1213▕     /**
    1214▕      * Get the Doctrine DBAL database connection instance.

  1   phar://%AppData%/Invoker/resources/invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar://%AppData%/Invoker/resources/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBoxf4b902e0e9ad\Invoker\Factories\AttributeCollection::getColumns("App\Models\User")
```

**Comment by mechelon** [comment] 2023-07-24 08:52
Duplicate of #342

**Closed as completed** 2023-07-26 11:44 UTC
