### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

### ISSUE THREAD

**Issue by Nex-Otaku** [beyondcode/invoker-community#332] opened 2023-02-26 11:33 UTC
------
**OS**: win32
**Invoker Version**: 2.11.0
**Laravel Version**: 10.1.5
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModule%5CIiko%5CIikoOrder&time=1677411135426&project=remote-duaiNzYPZpXSBHjAu5Cjsd

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1112
    1108▕     public function getDoctrineSchemaManager()
    1109▕     {
    1110▕         $connection = $this->getDoctrineConnection();
    1111▕ 
  ➜ 1112▕         return $connection->createSchemaManager();
    1113▕     }
    1114▕ 
    1115▕     /**
    1116▕      * Get the Doctrine DBAL database connection instance.

  1   phar:///tmp/root_invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:///tmp/root_invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox8e7f5be646a5\Invoker\Factories\AttributeCollection::getColumns("App\Module\Iiko\IikoOrder")
```

**Comment by Ahrengot** [comment] 2023-02-27 21:32
Same for me.

**OS**: darwin
**Invoker Version**: 2.11.0
**Laravel Version**: 10.0.0
**Local project**: true
**PHP Binary**: /opt/homebrew/bin/php
**Route**: /project/index?class=App%5CModels%5CUser&time=1677533484571&project=local-37Q645K83DNQqcPxJvEDJc

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at /Users/ahrengot/Valet Sites/agon-certificates/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1112
    1108▕     public function getDoctrineSchemaManager()
    1109▕     {
    1110▕         $connection = $this->getDoctrineConnection();
    1111▕ 
  ➜ 1112▕         return $connection->createSchemaManager();
    1113▕     }
    1114▕ 
    1115▕     /**
    1116▕      * Get the Doctrine DBAL database connection instance.

  1   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox8e7f5be646a5\Invoker\Factories\AttributeCollection::getColumns("App\Models\User")
```

**Comment by dqfan2012** [comment] 2023-02-28 01:23
I'm having the same issue. Windows 11. Local project running with Windows Valet.

**Invoker Version**: 2.11.0
**Laravel Version**: 10.1.5
**PHP Binary**: C:/php/php.exe
**Route**: /project/index?class=App%5CModels%5CUser&time=1677533484571&project=local-37Q645K83DNQqcPxJvEDJc

Exact same error as the two above.

**Comment by mechelon** [comment] 2023-03-01 16:05
Can you all check your `composer.lock` file for the installed `doctrine/dbal` version? And which PHP version are you using?

**Comment by marcreichel** [comment] 2023-03-01 16:41
I'm having the same issue.

**Invoker Version**: 2.11.0
**Laravel Version**: 10.1.5
**PHP Version**: 8.1.16
**doctrine/dbal**: 3.6.0

**Comment by Nex-Otaku** [comment] 2023-03-02 18:10
Same as above. 

It's a fresh installation, I created new project two weeks ago.

**Invoker Version:** 2.11.0
**Laravel Version:** 10.1.5
**PHP Version:** 8.1.16
**doctrine/dbal Version:** 3.6.0

**Comment by mechelon** [comment] 2023-03-03 11:37
We were able to reproduce the bug and will release a fix soon. Thank you all!

**Comment by jetwes** [comment] 2023-03-07 07:26
same here - can't do barely anything

**Comment by saiht** [comment] 2023-03-14 13:33
Any updates for this error?

Ping @mechelon @mpociot

**Comment by jetwes** [comment] 2023-03-15 13:13
Since i bought the license i can't use invoker at all...

**Comment by sschlein** [comment] 2023-03-16 09:18
Hey, this will be fixed with an update in the next 2-3 hours – sorry for the delay and missing communication!

**Comment by jetwes** [comment] 2023-03-16 15:24
Update available. Not working either.

**Comment by jetwes** [comment] 2023-03-16 15:27
------
**OS**: darwin
**Invoker Version**: 2.12.0
**Laravel Version**: 10.3.3
**Local project**: true
**PHP Binary**: /opt/homebrew/bin/php
**Route**: /project/index?class=App%5CModels%5CDomain&time=1678980332422&project=local-jZNTZYSDz4Dj3Cu1rXzi53

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

**Comment by Ahrengot** [comment] 2023-03-16 18:10
The auto-updater in the app kept failing for me. It Never updated, just downloaded rebooted and told me there was an update.

I completely wiped Invoker from the system using Clean My Mac and downloaded from the website. Now it boots without any issues, but when previewing mail, which is my primary use case for invoker, I'm hitting this issue now instead: https://github.com/beyondcode/invoker-community/issues/331

**Comment by marcreichel** [comment] 2023-03-20 08:55
Same here. The auto-updater failed which led to an unusable Invoker app. When starting it only shows a notification that Invoker is updating and will restart automatically. Which never happened. So I deleted Invoker completely and downloaded it again.

But the Doctrine error is still there:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/7645035/226291099-def416bc-dcb6-413f-9ff4-a514545e9a82.png">

------
**OS**: darwin
**Invoker Version**: 2.12.0
**Laravel Version**: 10.1.5
**Local project**: unknown
**PHP Binary**: /opt/homebrew/bin/php
**Route**: /project/index?class=App%5CModels%5CIssue&time=1679302261698&project=remote-fN5hoomvKCBAdgrVuJ3YZg

**Error**:
```
In Connection.php line 1112:
                                                                            
  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()
```

**Comment by mpociot** [comment] 2023-03-20 08:59
@marcreichel Could you help me figure out how to reproduce this?
Could you paste the content of your `composer.json` file?
I tried (so I thought) all possible Laravel + PHP + Doctrine version combinations, but looks like I missed something.

**Comment by marcreichel** [comment] 2023-03-20 09:04
@mpociot Sure. When I open Invoker, navigate to one of my models and trying to refresh the model definition the error gets thrown.

An example `composer.json` from one of my projects currently looks like this:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/socialite": "^5.5",
        "laravel/telescope": "^4.12",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.11",
        "pusher/pusher-php-server": "^7.2",
        "socialiteproviders/github": "^4.1",
        "doctrine/dbal": "^3.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.4",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan telescope:publish --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

**Comment by mpociot** [comment] 2023-03-20 09:23
Thank you @marcreichel!
Unfortunately, I can't reproduce it with the composer.json either.

Could you try the following:

Quit Invoker
Delete ~/Library/Logs/Invoker/renderer.log
Open Invoker and load your example project

If you then check the `renderer.log` file, you should see something like this:

```
[2023-03-20 10:20:56.793] [info]  Home :: checkLaravelVersion :: version ^10.0
[2023-03-20 10:20:56.793] [info]  Home :: checkLaravelVersion :: parsed version 10
```

And some lines further down:

```
[2023-03-20 10:20:56.806] [info]  Invoker :: invokerPath /Applications/Invoker.app/Contents/Resources/invoker_l10.phar
```

Could you see if it successfully detects the laravel version for you, and which phar filename it uses for the "invokerPath"?

**Comment by marcreichel** [comment] 2023-03-20 10:05
@mpociot

Seems to be all fine:

```
[2023-03-20 11:04:13.939] [info]  Home :: checkLaravelVersion :: version ^10.0
[2023-03-20 11:04:13.939] [info]  Home :: checkLaravelVersion :: parsed version 10
```

```
[2023-03-20 11:04:13.952] [info]  Invoker :: invokerPath /Applications/Invoker.app/Contents/Resources/invoker_l10.phar
```

**Comment by marcreichel** [comment] 2023-03-20 10:07
@mpociot I think I got it:

In a local project it is working just fine. The problem only occurs, when connecting via SSH to a project.

**Comment by mpociot** [comment] 2023-03-20 10:10
@marcreichel When you connect via SSH, the renderer.log should show something similar:

```
[2023-03-20 11:09:07.227] [info]  SSH :: checkProject :: version ^10.0
[2023-03-20 11:09:07.228] [info]  SSH :: checkProject :: parsed version 10
[2023-03-20 11:09:07.228] [info]  SSH :: checkProject :: version ok
[2023-03-20 11:09:07.229] [info]  SSH :: uploadInvoker :: laravel version :: 10
[2023-03-20 11:09:07.229] [info]  SSH :: execute :: request test -f "/tmp/forge_10_invoker.phar" && echo "true" || echo "false"
```

Could you see if this is in your log file?

**Comment by marcreichel** [comment] 2023-03-20 10:13
@mpociot 

It is (including an additional empty `execute` line):

```
[2023-03-20 11:11:20.489] [info]  SSH :: checkProject :: version ^10.0
[2023-03-20 11:11:20.489] [info]  SSH :: checkProject :: parsed version 10
[2023-03-20 11:11:20.489] [info]  SSH :: checkProject :: version ok
[2023-03-20 11:11:20.489] [info]  SSH :: uploadInvoker :: laravel version :: 10
[2023-03-20 11:11:20.489] [info]  SSH :: execute ::
[2023-03-20 11:11:20.489] [info]  SSH :: execute :: request test -f "/tmp/forge_10_invoker.phar" && echo "true" || echo "false"
```

**Comment by marcreichel** [comment] 2023-03-20 10:16
Wait a second. The error somehow disappeared and is not showing up anymore?! 🤔 It is now working both locally and remotely.

Maybe some sort of cache? 🤔 

I've no idea what I might have changed except starting and quitting Invoker multiple times over the last minutes to check the log file. 😄

**Comment by mpociot** [comment] 2023-03-20 10:19
Huh...those are the best kind of bugs 😂 

Well...I'm glad it is now working for you. I'll still try to reproduce this locally by downgrading to the older version and see if I can trigger it somehow. Maybe it is some weird kind of cache 🤔

**Comment by marcreichel** [comment] 2023-03-20 10:21
More of the weirdest kind of bugs imho 😄

Thanks for “sorting this out” somehow, nevertheless 👍🏼😄

**Closed as completed** 2023-05-12 08:00 UTC
