### ISSUE TITLE
Again the undefined method Doctrine\DBAL\Connection::createSchemaManager() message

### ISSUE THREAD

**Issue by domthomas-dev** [beyondcode/invoker-community#350] opened 2023-08-11 10:02 UTC
Hi
I want to use invoker to my ssh project.
I see different issue about this, but I tried every "solution" without effect : 
- My version is ok
- I deleted `/tmp/forge_10_invoker.phar` on the server
- I try to see in the rendered.log, but I see the error message off course
- My dbal version is 3.6.5 like this : https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/schema-manager.html
- on a local project, Invoker don't work. I'm using Herd ....
    
------
**OS**: darwin
**Invoker Version**: 2.13.0
**Laravel Version**: 10.6.2
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CActivity&time=1691747584746&project=remote-4orbhbjUSF8vMYjVwvgU8t

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at pim-prod.arstime.tech/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1145
    1141▕     public function getDoctrineSchemaManager()
    1142▕     {
    1143▕         $connection = $this->getDoctrineConnection();
    1144▕ 
  ➜ 1145▕         return $connection->createSchemaManager();
    1146▕     }
    1147▕ 
    1148▕     /**
    1149▕      * Get the Doctrine DBAL database connection instance.

  1   phar:///tmp/forge_10_invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:///tmp/forge_10_invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox0aaa99c27ffd\Invoker\Factories\AttributeCollection::getColumns()
```

**Comment by mechelon** [comment] 2023-08-14 08:54
Which PHP version are you using?

**Comment by mechelon** [comment] 2023-08-14 08:58
Duplicate of #342

**Closed as completed by mechelon** 2023-08-14 08:58 UTC
