### ISSUE TITLE
[feature request] ability to hide some models in the UI

### ISSUE THREAD

**Issue by Gompje** [beyondcode/invoker-community#54] opened 2021-02-02 18:03 UTC
I have a multi-tenant app. Some models are for the tenants only and use specific connection settings for them to run. 
I do not need to see those models, I even don't want to be able to! :)

For me a solution would be to simple be able to hide some models. Favo would work too. 🤔   or is this already possible?

**Comment by mpociot** [comment] 2021-02-02 21:04
How would you like to hide them? Configure it in the UI, or in your codebase (for example a docblock added to the model classes).

**Comment by mechelon** [comment] 2021-06-25 10:04
Duplicate of #100

**Closed by mechelon** 2021-06-25 10:04 UTC
Labels: feature request
