### ISSUE TITLE
Error - doctrine/dbal

### ISSUE THREAD

**Issue by michaelkorshun** [beyondcode/invoker-community#211] opened 2021-06-10 13:44 UTC
Project without vendor "doctrine/dbal" - works correctly.

------
**OS**: darwin
**Invoker Version**: 2.5.0
**Laravel Version**: 8.45.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5COrderProduct&time=1623332215944&project=local-uXCUfUWHqJy9qmnUBVGQnH

**Error**:
```
Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = Array) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41
     37▕     public function getServerVersion()
     38▕     {
     39▕         return \PDO::getAttribute(\PDO::ATTR_SERVER_VERSION);
     40▕     }
  ➜  41▕     public function prepare($sql, $driverOptions = [])
     42▕     {
     43▕         try {
     44▕             $statement = parent::prepare($sql, $driverOptions);
     45▕             \assert($statement instanceof \PDOStatement);


   Whoops\Exception\ErrorException 

  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = Array) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41
     37▕     public function getServerVersion()
     38▕     {
     39▕         return \PDO::getAttribute(\PDO::ATTR_SERVER_VERSION);
     40▕     }
  ➜  41▕     public function prepare($sql, $driverOptions = [])
     42▕     {
     43▕         try {
     44▕             $statement = parent::prepare($sql, $driverOptions);
     45▕             \assert($statement instanceof \PDOStatement);

      [2m+1 vendor frames [22m
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

**Comment by sschlein** [comment] 2021-06-10 13:46
Duplicate of #205 

Will be fixed with 2.5.1

**Closed by sschlein** 2021-06-10 13:46 UTC
