### ISSUE TITLE
Invoker can't find a method it requires from dependency Doctrine\DBAL class Connection

### ISSUE THREAD

**Issue by Blindmikey** [beyondcode/invoker-community#344] opened 2023-06-20 00:22 UTC
------
**OS**: win32
**Invoker Version**: 2.13.0
**Laravel Version**: 10.13.5
**Local project**: unknown
**PHP Binary**: C:\tools\php82\php.exe
**Route**: /project/show?id=1&class=App%5CModels%5CCategory&project=remote-wDiYWMphaapif7ny9RcxsA

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1210
    1206▕     public function getDoctrineSchemaManager()
    1207▕     {
    1208▕         $connection = $this->getDoctrineConnection();
    1209▕ 
  ➜ 1210▕         return $connection->createSchemaManager();
    1211▕     }
    1212▕ 
    1213▕     /**
    1214▕      * Get the Doctrine DBAL database connection instance.

  1   phar:///tmp/vagrant_10_invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:///tmp/vagrant_10_invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox0aaa99c27ffd\Invoker\Factories\AttributeCollection::getColumns()
```

**Comment by mechelon** [comment] 2023-06-22 15:25
Can you share the content of your composer.json file?

**Comment by Blindmikey** [comment] 2023-06-22 17:15
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "classic-o/nova-media-library": "dev-nova-4",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/nova": "~4.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "m-a-k-o/nova-custom-table-card": "^4.0",
        "optimistdigital/nova-sortable": "^3.4",
        "outl1ne/nova-multiselect-field": "^4.3",
        "outl1ne/nova-settings": "^5.1",
        "outofoffice/password-generator": "^1.8",
        "spatie/simple-excel": "^3.2"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.21",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "onecentlin/laravel-adminer": "^6.1",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://nova.laravel.com"
        },
        {
            "type": "vcs",
            "url":  "git@github.com:the-alichemist/nova-media-library.git"
        }
    ]
}

```

**Comment by mechelon** [comment] 2023-07-24 08:52
Duplicate of #342

**Closed as completed** 2023-08-14 09:49 UTC
