### ISSUE TITLE
Declaration of Doctrine... must be compatible with... PDO

### ISSUE THREAD

**Issue by palamike** [beyondcode/invoker-community#208] opened 2021-06-06 04:19 UTC
Hi,

I have 2 laravel projects.

However, 1 project have error in invoker latest version. 

But another one is fine.

I already check MySQL is working.

I try to run composer update but it still errors.

------
**OS**: darwin
**Invoker Version**: 2.5.0
**Laravel Version**: 8.45.1
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CInvoice&time=1622952863647&project=remote-573rbdudnSf8sbnUEy4wGg

**Error**:
```
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = Array) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement in phar:///tmp/billyapp_invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 41
```

**Comment by tfevens** [comment] 2021-06-07 11:16
Duplicate of #205

**Comment by sschlein** [comment] 2021-06-10 08:13
Closeing this because of duplication #205

**Closed by sschlein** 2021-06-10 08:13 UTC
