### ISSUE TITLE
Error when Telescope is in require-dev only

### ISSUE THREAD

**Issue by ziming** [beyondcode/invoker-community#140] opened 2021-02-19 04:35 UTC
This happens when I try to connect to my production laravel app. Telescope is in require-dev

------
**OS**: darwin
**Invoker Version**: 2.0.2
**Laravel Version**: 8.28.1
**PHP Binary**: /usr/local/bin/php

**Error**:
```
In TelescopeServiceProvider.php line 10:
                                                                           
  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found
```

**Comment by voicecode-bv** [comment] 2021-02-24 15:59
Duplicate of #121

**Comment by mpociot** [comment] 2021-02-25 08:33
Closing this in favor of #121

**Closed by mpociot** 2021-02-25 08:33 UTC
