### ISSUE TITLE
jsonb column error.

### ISSUE THREAD

**Issue by bsormagec** [beyondcode/invoker-community#63] opened 2021-02-03 08:00 UTC
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CVehicleHistory&time=1612339187513&project=local-pBXa2mwuFRkgLphz4tSiN4

**Error**:
```
_HumbugBox7091da86deae\Doctrine\DBAL\Exception 

  Unknown database type jsonb requested, _HumbugBox7091da86deae\Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:179
    175|             $this->initializeAllDoctrineTypeMappings();
    176|         }
    177|         $dbType = \strtolower($dbType);
    178|         if (!isset($this->doctrineTypeMapping[$dbType])) {
  > 179|             throw new \_HumbugBox7091da86deae\Doctrine\DBAL\Exception('Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.');
    180|         }
    181|         return $this->doctrineTypeMapping[$dbType];
    182|     }
    183|     public function hasDoctrineTypeMappingFor($dbType)

      [2m+3 vendor frames [22m
  4   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:35
      _HumbugBox7091da86deae\Doctrine\DBAL\Schema\AbstractSchemaManager::listTableColumns("companies")

  5   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox7091da86deae\Invoker\Factories\AttributeCollection::getColumns("App\Company")
```

**Comment by sschlein** [comment] 2021-02-03 08:46
Duplicate of https://github.com/beyondcode/invoker-community/issues/47

**Closed by sschlein** 2021-02-03 08:46 UTC
